GRANT USAGE ON SCHEMA core TO mobility_app;
GRANT SELECT ON ALL TABLES IN SCHEMA core TO mobility_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA core GRANT SELECT ON TABLES TO mobility_app;

GRANT USAGE ON SCHEMA staging TO mobility_app;
GRANT INSERT ON ALL TABLES IN SCHEMA staging TO mobility_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA staging GRANT INSERT ON TABLES TO mobility_app;

GRANT USAGE ON SCHEMA etl TO mobility_app;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA etl TO mobility_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA etl GRANT EXECUTE ON FUNCTIONS TO mobility_app;

ALTER ROLE mobility_app IN DATABASE mobility SET search_path = core, public;
